version: '3'
services:
  backend:
    image: ai_facial_emotion_prediction_system_backend
    container_name: backend
    networks:
      - ai_network
  frontend:
    image: ai_facial_emotion_prediction_system_frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - ai_network
  video_app:
    image: ai_facial_emotion_prediction_system_video_app
    container_name: video_app
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
