version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    container_name: emotion_backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: emotion_frontend

  video_prediction:
    build:
      context: ./video_prediction
    volumes:
      - ./video_prediction:/app
    container_name: emotion_video_prediction
